name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  rxdart: ^0.18.1
#  shared_preferences:
#  diacritic:
#  intl: any
#  flutter_widget_from_html_core: ^0.2.4+3
#  flutter_markdown: ^0.2.0
#  html2md: ^0.5.1
#  otp_consent: 1.0.3
#
#  dio: ^3.0.9
#  primitive_type_parser: ^0.0.2
#  lightweight_bloc: 0.0.5+4
#  sqflite: 1.1.0
#
#  url_launcher: ^5.0.0
#  base_webview:
#  flutter_svg: ^0.17.4
#
#  settings:
#  animations: ^1.0.0+5
#  flutter_staggered_grid_view: ^0.2.2
#  sensors: ^0.4.0+1
#  vibrate:
#
#  carousel_slider: 2.1.0
#  flutter_swiper: ^1.1.6
#  flutter_advanced_networkimage: ^0.6.0
#
#  cached_network_image: ^2.0.0-rc.1
#  http: 0.12.0+2
#
#  video_player: 0.11.1+2
#  open_iconic_flutter: ">=0.3.0 <0.4.0"
#  image:
#  rect_getter: ^0.0.1
#  html:    ^0.14.0+3
#  shimmer: ^0.0.5
#  flutter_html:    ^0.11.1
#  device_info:
#  audioplayers:
#  spritewidget:    ^0.9.23
#
#  contacts_service:
#  path_drawing:    ^0.4.0
#  oktoast: 2.2.0
#  flutter_redux:   0.5.3
#
#  memory_image_converter:  0.0.1
#  gradient_app_bar:    0.0.1
#  redux:   3.0.0
#  synchronized:    ^1.5.1+1
#  crypto_keys: 0.1.0
#  pattern_formatter:   1.0.1
#
#  crypto:  ^2.1.2
#  asn1lib: 0.5.8
#  modal_progress_hud: ^0.1.3
#  share:
#  toast: ^0.1.4
#
#  ordered_set: ^1.1.2
#  path_provider: 1.6.18
#  box2d_flame: ^0.4.2
#  tiled: ^0.2.0
#
#  convert: ^2.0.1
#  google_api_availability:
#  meta: ^1.1.6
#
#  image_downloader:
#
#  flutter_slidable:
#    git:
#      url: https://github.com/hnvn/flutter_slidable.git
#
#  transparent_image:
#  vibration:
#  flutter_cupertino_date_picker: ^1.0.2
#  progress_hud: 1.1.0
#  ansicolor: 1.0.2
#
#  percent_indicator: ^2.1.1
#  app_settings:
#  flutter_rating_bar: ^2.0.0+2
#  autocomplete_textfield: 1.6.6
#
#  webview_flutter: ^0.3.19+7
#  flutter_picker: ^1.0.13
#  flutter_xlider: ^2.5.2
#  pin_code_text_field: 1.4.0
#
#  countdown_flutter:
#  keyboard_actions: ^2.1.2
#  flutter_spinkit: ^4.0.0
#  package_info: ^0.4.0+6
#
#  validators: ^2.0.0
#  tiengviet: ^0.2.2
#  android_intent: ^0.3.2
#  sticky_headers: ^0.1.8
#
#  extended_image: ^0.8.0
#  scrollable_positioned_list: 0.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
